const ERP_SCHEMA = `
-- ========== PRODUCTS ==========
CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(80) PRIMARY KEY,
  type ENUM('physical','digital','service') NOT NULL DEFAULT 'physical',
  name VARCHAR(500) NOT NULL,
  name_en VARCHAR(500) DEFAULT NULL,
  name_es VARCHAR(500) DEFAULT NULL,
  slug VARCHAR(255) DEFAULT NULL,
  description TEXT,
  description_en TEXT,
  description_es TEXT,
  category VARCHAR(255) DEFAULT NULL,
  subcategory VARCHAR(255) DEFAULT NULL,
  brand VARCHAR(255) DEFAULT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  cost_price DECIMAL(12,2) DEFAULT 0,
  compare_at_price DECIMAL(12,2) DEFAULT NULL,
  currency VARCHAR(10) DEFAULT 'BRL',
  sku VARCHAR(255) DEFAULT NULL,
  barcode VARCHAR(255) DEFAULT NULL,
  stock INT DEFAULT 0,
  low_stock_threshold INT DEFAULT 5,
  track_stock TINYINT(1) DEFAULT 1,
  weight DECIMAL(10,3) DEFAULT NULL,
  weight_unit VARCHAR(10) DEFAULT 'g',
  dimensions JSON DEFAULT NULL,
  images JSON DEFAULT NULL,
  featured_image VARCHAR(500) DEFAULT NULL,
  technical_specs JSON DEFAULT NULL,
  seo_title VARCHAR(500) DEFAULT NULL,
  seo_description VARCHAR(500) DEFAULT NULL,
  tags JSON DEFAULT NULL,
  is_featured TINYINT(1) DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  is_digital TINYINT(1) DEFAULT 0,
  digital_file VARCHAR(500) DEFAULT NULL,
  visibility ENUM('public','private','hidden') DEFAULT 'public',
  meta JSON DEFAULT NULL,
  persona_id VARCHAR(60) DEFAULT NULL,
  owner_id VARCHAR(60) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_product_slug (slug),
  KEY idx_product_type (type),
  KEY idx_product_category (category),
  KEY idx_product_active (is_active),
  KEY idx_product_featured (is_featured),
  KEY idx_product_owner (owner_id),
  KEY idx_product_persona (persona_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== PRODUCT VARIANTS ==========
CREATE TABLE IF NOT EXISTS product_variants (
  id VARCHAR(80) PRIMARY KEY,
  product_id VARCHAR(80) NOT NULL,
  name VARCHAR(255) NOT NULL,
  sku VARCHAR(255) DEFAULT NULL,
  barcode VARCHAR(255) DEFAULT NULL,
  price DECIMAL(12,2) DEFAULT NULL,
  cost_price DECIMAL(12,2) DEFAULT NULL,
  compare_at_price DECIMAL(12,2) DEFAULT NULL,
  stock INT DEFAULT 0,
  low_stock_threshold INT DEFAULT 5,
  weight DECIMAL(10,3) DEFAULT NULL,
  weight_unit VARCHAR(10) DEFAULT 'g',
  dimensions JSON DEFAULT NULL,
  image VARCHAR(500) DEFAULT NULL,
  options JSON DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  position INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_variant_product (product_id),
  KEY idx_variant_sku (sku),
  CONSTRAINT fk_variant_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== CATEGORIES ==========
CREATE TABLE IF NOT EXISTS product_categories (
  id VARCHAR(80) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) DEFAULT NULL,
  name_es VARCHAR(255) DEFAULT NULL,
  slug VARCHAR(255) DEFAULT NULL,
  description TEXT,
  image VARCHAR(500) DEFAULT NULL,
  icon VARCHAR(100) DEFAULT NULL,
  parent_id VARCHAR(80) DEFAULT NULL,
  position INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  product_type ENUM('physical','digital','service','all') DEFAULT 'all',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_category_parent (parent_id),
  KEY idx_category_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== ORDERS ==========
CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(80) PRIMARY KEY,
  order_number VARCHAR(50) NOT NULL,
  customer_id VARCHAR(60) DEFAULT NULL,
  customer_name VARCHAR(255) DEFAULT NULL,
  customer_email VARCHAR(255) DEFAULT NULL,
  customer_phone VARCHAR(50) DEFAULT NULL,
  customer_document VARCHAR(30) DEFAULT NULL,
  status ENUM('pending','confirmed','paid','processing','shipped','delivered','cancelled','refunded','expired') NOT NULL DEFAULT 'pending',
  payment_status ENUM('pending','paid','partial','refunded','failed','expired') NOT NULL DEFAULT 'pending',
  fulfillment_status ENUM('unfulfilled','partial','fulfilled','returned') NOT NULL DEFAULT 'unfulfilled',
  source ENUM('whatsapp','telegram','web','api','manual') NOT NULL DEFAULT 'web',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount DECIMAL(12,2) DEFAULT 0,
  shipping DECIMAL(12,2) DEFAULT 0,
  tax DECIMAL(12,2) DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) DEFAULT 'BRL',
  coupon_code VARCHAR(100) DEFAULT NULL,
  notes TEXT,
  internal_notes TEXT,
  shipping_address JSON DEFAULT NULL,
  billing_address JSON DEFAULT NULL,
  payment_method ENUM('pix','credit_card','debit_card','bank_transfer','cash','boleto','other') DEFAULT NULL,
  payment_reference VARCHAR(255) DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  persona_id VARCHAR(60) DEFAULT NULL,
  owner_id VARCHAR(60) DEFAULT NULL,
  ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  shipped_at TIMESTAMP NULL DEFAULT NULL,
  delivered_at TIMESTAMP NULL DEFAULT NULL,
  cancelled_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_order_number (order_number),
  KEY idx_order_customer (customer_id),
  KEY idx_order_status (status),
  KEY idx_order_payment_status (payment_status),
  KEY idx_order_source (source),
  KEY idx_order_owner (owner_id),
  KEY idx_order_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== ORDER ITEMS ==========
CREATE TABLE IF NOT EXISTS order_items (
  id VARCHAR(80) PRIMARY KEY,
  order_id VARCHAR(80) NOT NULL,
  product_id VARCHAR(80) DEFAULT NULL,
  variant_id VARCHAR(80) DEFAULT NULL,
  title VARCHAR(500) NOT NULL,
  subtitle VARCHAR(500) DEFAULT NULL,
  type ENUM('physical','digital','service','shipping','discount','fee') NOT NULL DEFAULT 'physical',
  quantity INT NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL,
  unit_cost DECIMAL(12,2) DEFAULT 0,
  discount DECIMAL(12,2) DEFAULT 0,
  total DECIMAL(12,2) NOT NULL,
  image VARCHAR(500) DEFAULT NULL,
  specs JSON DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_item_order (order_id),
  KEY idx_item_product (product_id),
  CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== DELIVERIES ==========
CREATE TABLE IF NOT EXISTS deliveries (
  id VARCHAR(80) PRIMARY KEY,
  order_id VARCHAR(80) NOT NULL,
  tracking_code VARCHAR(255) DEFAULT NULL,
  carrier VARCHAR(255) DEFAULT NULL,
  carrier_service VARCHAR(255) DEFAULT NULL,
  status ENUM('pending','picked_up','in_transit','out_for_delivery','delivered','failed','returned') NOT NULL DEFAULT 'pending',
  estimated_delivery DATE DEFAULT NULL,
  shipped_at TIMESTAMP NULL DEFAULT NULL,
  delivered_at TIMESTAMP NULL DEFAULT NULL,
  shipping_address JSON DEFAULT NULL,
  weight DECIMAL(10,3) DEFAULT NULL,
  dimensions JSON DEFAULT NULL,
  cost DECIMAL(12,2) DEFAULT 0,
  tracking_url VARCHAR(500) DEFAULT NULL,
  tracking_events JSON DEFAULT NULL,
  notes TEXT,
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_delivery_order (order_id),
  KEY idx_delivery_tracking (tracking_code),
  KEY idx_delivery_status (status),
  CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== STOCK MOVEMENTS ==========
CREATE TABLE IF NOT EXISTS stock_movements (
  id VARCHAR(80) PRIMARY KEY,
  product_id VARCHAR(80) DEFAULT NULL,
  variant_id VARCHAR(80) DEFAULT NULL,
  type ENUM('in','out','adjustment','return','reserved','released','loss') NOT NULL,
  quantity INT NOT NULL,
  previous_stock INT DEFAULT NULL,
  new_stock INT DEFAULT NULL,
  reason VARCHAR(500) DEFAULT NULL,
  order_id VARCHAR(80) DEFAULT NULL,
  reference VARCHAR(255) DEFAULT NULL,
  cost_per_unit DECIMAL(12,2) DEFAULT NULL,
  owner_id VARCHAR(60) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_stock_product (product_id),
  KEY idx_stock_variant (variant_id),
  KEY idx_stock_type (type),
  KEY idx_stock_order (order_id),
  KEY idx_stock_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== TRANSACTIONS ==========
CREATE TABLE IF NOT EXISTS transactions (
  id VARCHAR(80) PRIMARY KEY,
  type ENUM('income','expense','refund','transfer','adjustment') NOT NULL,
  category VARCHAR(100) DEFAULT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'BRL',
  payment_method ENUM('pix','credit_card','debit_card','bank_transfer','cash','boleto','other') DEFAULT NULL,
  status ENUM('pending','confirmed','cancelled','failed') NOT NULL DEFAULT 'pending',
  order_id VARCHAR(80) DEFAULT NULL,
  customer_id VARCHAR(60) DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  reference VARCHAR(255) DEFAULT NULL,
  external_id VARCHAR(255) DEFAULT NULL,
  proof_url VARCHAR(500) DEFAULT NULL,
  due_date DATE DEFAULT NULL,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  owner_id VARCHAR(60) DEFAULT NULL,
  persona_id VARCHAR(60) DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_transaction_type (type),
  KEY idx_transaction_category (category),
  KEY idx_transaction_status (status),
  KEY idx_transaction_order (order_id),
  KEY idx_transaction_customer (customer_id),
  KEY idx_transaction_date (created_at),
  KEY idx_transaction_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== PAYMENT LINKS ==========
CREATE TABLE IF NOT EXISTS payment_links (
  id VARCHAR(80) PRIMARY KEY,
  order_id VARCHAR(80) DEFAULT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'BRL',
  provider ENUM('mercadopago','paghiper','stripe','manual','other') DEFAULT 'mercadopago',
  provider_id VARCHAR(255) DEFAULT NULL,
  payment_url VARCHAR(500) DEFAULT NULL,
  qr_code_base64 TEXT DEFAULT NULL,
  pix_code VARCHAR(500) DEFAULT NULL,
  status ENUM('active','paid','expired','cancelled') NOT NULL DEFAULT 'active',
  customer_id VARCHAR(60) DEFAULT NULL,
  customer_email VARCHAR(255) DEFAULT NULL,
  customer_document VARCHAR(30) DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_payment_order (order_id),
  KEY idx_payment_status (status),
  KEY idx_payment_provider (provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== SITE SECTIONS (CMS) ==========
CREATE TABLE IF NOT EXISTS site_sections (
  id VARCHAR(80) PRIMARY KEY,
  section_key VARCHAR(100) NOT NULL,
  type ENUM('hero','features','cta','testimonials','faq','banner','how_it_works','pricing','gallery','custom') NOT NULL DEFAULT 'custom',
  title JSON DEFAULT NULL,
  subtitle JSON DEFAULT NULL,
  content JSON DEFAULT NULL,
  items JSON DEFAULT NULL,
  settings JSON DEFAULT NULL,
  media_ids JSON DEFAULT NULL,
  position INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  persona_id VARCHAR(60) DEFAULT NULL,
  language VARCHAR(10) DEFAULT 'pt-BR',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_section_key (section_key, language),
  KEY idx_section_type (type),
  KEY idx_section_active (is_active),
  KEY idx_section_persona (persona_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== NOTIFICATIONS ==========
CREATE TABLE IF NOT EXISTS notifications (
  id VARCHAR(80) PRIMARY KEY,
  type ENUM('order_created','order_paid','order_shipped','order_delivered','order_cancelled','payment_reminder','payment_overdue','delivery_update','stock_alert','custom') NOT NULL,
  channel ENUM('whatsapp','telegram','email','web','push') NOT NULL DEFAULT 'whatsapp',
  recipient_id VARCHAR(60) DEFAULT NULL,
  recipient_name VARCHAR(255) DEFAULT NULL,
  recipient_phone VARCHAR(50) DEFAULT NULL,
  recipient_email VARCHAR(255) DEFAULT NULL,
  message TEXT,
  title VARCHAR(255) DEFAULT NULL,
  status ENUM('pending','sent','delivered','read','failed') NOT NULL DEFAULT 'pending',
  related_id VARCHAR(80) DEFAULT NULL,
  related_type VARCHAR(50) DEFAULT NULL,
  scheduled_at TIMESTAMP NULL DEFAULT NULL,
  sent_at TIMESTAMP NULL DEFAULT NULL,
  read_at TIMESTAMP NULL DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  owner_id VARCHAR(60) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_notification_type (type),
  KEY idx_notification_recipient (recipient_id),
  KEY idx_notification_status (status),
  KEY idx_notification_scheduled (scheduled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== SUPPLIERS ==========
CREATE TABLE IF NOT EXISTS suppliers (
  id VARCHAR(80) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  trade_name VARCHAR(255) DEFAULT NULL,
  document VARCHAR(30) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  whatsapp VARCHAR(50) DEFAULT NULL,
  address JSON DEFAULT NULL,
  city VARCHAR(100) DEFAULT NULL,
  state VARCHAR(10) DEFAULT NULL,
  country VARCHAR(100) DEFAULT 'Brasil',
  website VARCHAR(500) DEFAULT NULL,
  contact_name VARCHAR(255) DEFAULT NULL,
  contact_role VARCHAR(100) DEFAULT NULL,
  category VARCHAR(100) DEFAULT NULL,
  tags JSON DEFAULT NULL,
  notes TEXT,
  rating TINYINT DEFAULT NULL,
  payment_terms VARCHAR(255) DEFAULT NULL,
  delivery_time_days INT DEFAULT NULL,
  minimum_order DECIMAL(12,2) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  owner_id VARCHAR(60) DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_supplier_category (category),
  KEY idx_supplier_active (is_active),
  KEY idx_supplier_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== PURCHASE ORDERS ==========
CREATE TABLE IF NOT EXISTS purchase_orders (
  id VARCHAR(80) PRIMARY KEY,
  po_number VARCHAR(50) NOT NULL,
  supplier_id VARCHAR(80) DEFAULT NULL,
  status ENUM('draft','sent','confirmed','partial','received','cancelled') NOT NULL DEFAULT 'draft',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  shipping DECIMAL(12,2) DEFAULT 0,
  tax DECIMAL(12,2) DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) DEFAULT 'BRL',
  expected_date DATE DEFAULT NULL,
  received_date DATE DEFAULT NULL,
  notes TEXT,
  owner_id VARCHAR(60) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_po_number (po_number),
  KEY idx_po_supplier (supplier_id),
  KEY idx_po_status (status),
  KEY idx_po_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== PURCHASE ORDER ITEMS ==========
CREATE TABLE IF NOT EXISTS purchase_order_items (
  id VARCHAR(80) PRIMARY KEY,
  purchase_order_id VARCHAR(80) NOT NULL,
  product_id VARCHAR(80) DEFAULT NULL,
  variant_id VARCHAR(80) DEFAULT NULL,
  title VARCHAR(500) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  unit_cost DECIMAL(12,2) NOT NULL,
  total DECIMAL(12,2) NOT NULL,
  received_quantity INT DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_poi_order (purchase_order_id),
  KEY idx_poi_product (product_id),
  CONSTRAINT fk_poi_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== COUPON CODES ==========
CREATE TABLE IF NOT EXISTS coupon_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  type ENUM('percentage','fixed') NOT NULL DEFAULT 'percentage',
  value DECIMAL(12,2) NOT NULL,
  min_value DECIMAL(12,2) DEFAULT 0,
  max_uses INT DEFAULT NULL,
  used_count INT DEFAULT 0,
  description VARCHAR(500) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  owner_id VARCHAR(60) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_coupon_code (code),
  KEY idx_coupon_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========== COMMERCE CARTS ==========
CREATE TABLE IF NOT EXISTS commerce_carts (
  id VARCHAR(80) PRIMARY KEY,
  session_id VARCHAR(120) NOT NULL,
  user_id VARCHAR(60) DEFAULT NULL,
  persona_id VARCHAR(60) DEFAULT NULL,
  items JSON DEFAULT NULL,
  shipping_address JSON DEFAULT NULL,
  status ENUM('active','expired','completed','abandoned') DEFAULT 'active',
  flow_step ENUM('browsing','building_order','confirming_address','confirming_payment','confirming_order','completed') DEFAULT 'browsing',
  order_id VARCHAR(80) DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_cart_session (session_id),
  KEY idx_cart_user (user_id),
  KEY idx_cart_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
`;

module.exports = ERP_SCHEMA;