const path = require('path');

const KNOWLEDGE_SOURCES = [
  {
    id: 'imersao-vendas-mod1',
    name: 'Imersão Prospecção - Módulo 1: Onboarding',
    type: 'pdf',
    enabled: true,
    filePath: path.join(__dirname, '..', 'imersao-prospeccao-vendas', 'modulo-01-onboarding.pdf'),
    dataPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod1_documents.json'),
    indexPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod1_index.json'),
    searchFields: ['reference', 'text'],
    defaultTopK: 6,
    contextTemplate: {
      'pt-BR': 'CONHECIMENTO DE VENDAS ENCONTRADO:\n{context}\n\nUse esta informação para responder.',
      'en-US': 'SALES KNOWLEDGE FOUND:\n{context}\n\nUse this information to respond.',
      'es-ES': 'CONOCIMIENTO DE VENTAS ENCONTRADO:\n{context}\n\nUsa esta información para responder.',
    },
    sourceFormat: (docs) => docs.map(d => `${d.reference}: "${d.text}"`).join('\n'),
    ingester: 'pdf',
  },
  {
    id: 'imersao-vendas-mod2',
    name: 'Imersão Prospecção - Módulo 2: Abordagem',
    type: 'pdf',
    enabled: true,
    filePath: path.join(__dirname, '..', 'imersao-prospeccao-vendas', 'modulo-02-abordagem.pdf'),
    dataPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod2_documents.json'),
    indexPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod2_index.json'),
    searchFields: ['reference', 'text'],
    defaultTopK: 6,
    contextTemplate: {
      'pt-BR': 'CONHECIMENTO DE VENDAS ENCONTRADO:\n{context}\n\nUse esta informação para responder.',
      'en-US': 'SALES KNOWLEDGE FOUND:\n{context}\n\nUse this information to respond.',
      'es-ES': 'CONOCIMIENTO DE VENTAS ENCONTRADO:\n{context}\n\nUsa esta información para responder.',
    },
    sourceFormat: (docs) => docs.map(d => `${d.reference}: "${d.text}"`).join('\n'),
    ingester: 'pdf',
  },
  {
    id: 'imersao-vendas-mod3',
    name: 'Imersão Prospecção - Módulo 3: Aquisição',
    type: 'pdf',
    enabled: true,
    filePath: path.join(__dirname, '..', 'imersao-prospeccao-vendas', 'modulo-03-aquisicao.pdf'),
    dataPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod3_documents.json'),
    indexPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod3_index.json'),
    searchFields: ['reference', 'text'],
    defaultTopK: 6,
    contextTemplate: {
      'pt-BR': 'CONHECIMENTO DE VENDAS ENCONTRADO:\n{context}\n\nUse esta informação para responder.',
      'en-US': 'SALES KNOWLEDGE FOUND:\n{context}\n\nUse this information to respond.',
      'es-ES': 'CONOCIMIENTO DE VENTAS ENCONTRADO:\n{context}\n\nUsa esta información para responder.',
    },
    sourceFormat: (docs) => docs.map(d => `${d.reference}: "${d.text}"`).join('\n'),
    ingester: 'pdf',
  },
  {
    id: 'imersao-vendas-mod4',
    name: 'Imersão Prospecção - Módulo 4: Prospecção',
    type: 'pdf',
    enabled: true,
    filePath: path.join(__dirname, '..', 'imersao-prospeccao-vendas', 'modulo-04-prospeccao.pdf'),
    dataPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod4_documents.json'),
    indexPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod4_index.json'),
    searchFields: ['reference', 'text'],
    defaultTopK: 6,
    contextTemplate: {
      'pt-BR': 'CONHECIMENTO DE VENDAS ENCONTRADO:\n{context}\n\nUse esta informação para responder.',
      'en-US': 'SALES KNOWLEDGE FOUND:\n{context}\n\nUse this information to respond.',
      'es-ES': 'CONOCIMIENTO DE VENTAS ENCONTRADO:\n{context}\n\nUsa esta información para responder.',
    },
    sourceFormat: (docs) => docs.map(d => `${d.reference}: "${d.text}"`).join('\n'),
    ingester: 'pdf',
  },
  {
    id: 'imersao-vendas-mod5',
    name: 'Imersão Prospecção - Módulo 5: Decolagem',
    type: 'pdf',
    enabled: true,
    filePath: path.join(__dirname, '..', 'imersao-prospeccao-vendas', 'modulo-05-decolagem.pdf'),
    dataPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod5_documents.json'),
    indexPath: path.join(__dirname, '..', 'data', 'imersao-vendas-mod5_index.json'),
    searchFields: ['reference', 'text'],
    defaultTopK: 6,
    contextTemplate: {
      'pt-BR': 'CONHECIMENTO DE VENDAS ENCONTRADO:\n{context}\n\nUse esta informação para responder.',
      'en-US': 'SALES KNOWLEDGE FOUND:\n{context}\n\nUse this information to respond.',
      'es-ES': 'CONOCIMIENTO DE VENTAS ENCONTRADO:\n{context}\n\nUsa esta información para responder.',
    },
    sourceFormat: (docs) => docs.map(d => `${d.reference}: "${d.text}"`).join('\n'),
    ingester: 'pdf',
  },
];

module.exports = KNOWLEDGE_SOURCES;